// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nhghudkseqdmgajcwybz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5oZ2h1ZGtzZXFkbWdhamN3eWJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwOTAzMjUsImV4cCI6MjA2NDY2NjMyNX0.zE_Lan3ZCZPWnF4MiVwRkNlz0aSOn8DCvkBhS64gYiU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);